### PR TITLE
ci: auto label issues workflow

### LINKED ISSUE #2: GitHub Actions workflow is failing to assign labels automatically to the issues.
## Describe the bug
The GitHub Actions workflow is failing to assign labels automatically to the issues. The auto-label step in the workflow does not seem to be working as expected.

## To Reproduce
1. Open a new issue in the repository.
2. Observe that the issue does not get labeled automatically.
3. Check the workflow logs in the "Actions" tab for any errors related to the auto-label step.

## Expected behavior
The workflow should automatically assign labels to the issues based on the configuration.

## Additional context
- Ensure that the workflow is correctly configured.

### PR DESCRIPTION
**Pull request by priyanshuverma-dev**
## Description

Adds Auto labeler for issues

Fixes #2 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by priyanshuverma-dev** [comment]
@Lelin07 Please review the workflows

**Review by Lelin07 — CHANGES_REQUESTED** [review]
Hi @priyanshuverma-dev 

Thank you for your contribution. We already have an auto-label job in [greetings.yml](https://github.com/Lelin07/retro-green-theme/blob/main/.github/workflows/greetings.yml). I'm not sure if that's the right place for it to exist. Can we use the existing code in greetings.yml for auto-labeling? If not, please delete the existing job in greetings.yml and make changes accordingly.

Thanks!

**Comment by priyanshuverma-dev** [comment]
@Lelin07 I am not sure if it work with that as We need to test that. 
I think it is good to separate auto issue labeler. Because it triggers on edit also

**Review by Lelin07 — APPROVED** [review]

**Comment by Lelin07** [comment]
> @Lelin07 I am not sure if it work with that as We need to test that. I think it is good to separate auto issue labeler. Because it triggers on edit also

Sounds good to me. Ready to merge

**Review by Lelin07 — APPROVED** [review]

**Pull request merged**
